from __future__ import annotations

from datetime import datetime
from pathlib import Path

from .suggest import Suggestion


def _quote_for_alias(raw: str) -> str:
    return raw.replace("\\", "\\\\").replace('"', '\\"')


def _suggestion_snippet(suggestion: Suggestion, shell: str) -> str:
    if shell == "powershell":
        return (
            f"function {suggestion.name} {{\n"
            f"  {suggestion.command}\n"
            "}"
        )
    if suggestion.kind == "alias":
        return f'alias {suggestion.name}="{_quote_for_alias(suggestion.command)}"'
    return (
        f"{suggestion.name}() {{\n"
        f"  {suggestion.command}\n"
        "}"
    )


def resolve_profile_path(shell: str) -> Path:
    home = Path.home()
    if shell == "powershell":
        docs_profile = home / "Documents" / "PowerShell" / "Microsoft.PowerShell_profile.ps1"
        return docs_profile
    if shell == "zsh":
        return home / ".zshrc"
    return home / ".bashrc"


def managed_markers(shell: str) -> tuple[str, str]:
    start = f"# >>> ShellSensei ({shell}) >>>"
    end = "# <<< ShellSensei <<<"
    return start, end


def render_profile_block(suggestions: list[Suggestion], shell: str) -> str:
    start, end = managed_markers(shell)
    lines = [start, "# Auto-generated by ShellSensei. Manual edits inside this block may be overwritten."]
    for suggestion in suggestions:
        lines.append(_suggestion_snippet(suggestion, shell=shell))
        lines.append("")
    if lines[-1] == "":
        lines.pop()
    lines.append(end)
    return "\n".join(lines)


def upsert_managed_block(existing_text: str, new_block: str, shell: str) -> str:
    start, end = managed_markers(shell)
    existing = existing_text or ""

    start_idx = existing.find(start)
    end_idx = existing.find(end)
    if start_idx != -1 and end_idx != -1 and end_idx >= start_idx:
        end_idx += len(end)
        before = existing[:start_idx].rstrip()
        after = existing[end_idx:].lstrip()
        parts = [p for p in [before, new_block, after] if p]
        return "\n\n".join(parts) + "\n"

    if existing.strip():
        return existing.rstrip() + "\n\n" + new_block + "\n"
    return new_block + "\n"


def backup_profile(profile_path: Path) -> Path | None:
    if not profile_path.exists():
        return None
    ts = datetime.now().strftime("%Y%m%d%H%M%S")
    backup = profile_path.with_name(profile_path.name + f".bak-{ts}")
    backup.write_text(profile_path.read_text(encoding="utf-8", errors="ignore"), encoding="utf-8")
    return backup
